/*
 * Copyright 2022-2023, 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v10.0
processor: MIMXRT1189xxxxx
package_id: MIMXRT1189CVM8A
mcu_data: ksdk2_0
processor_version: 0.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
    BOARD_InitPhyAccessPins();
    BOARD_InitSwtPort0Pins();
    BOARD_InitSwtPort1Pins();
    BOARD_InitSwtPort2Pins();
    BOARD_InitSwtPort3Pins();
    BOARD_InitEpPins();
    BOARD_InitFlexSPIPins();
    BOARD_InitPPSPins();
    BOARD_InitHyperramPins();
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPPSPins
 * Description   : Configures pin routing and optionally pin electrical features for PPS signal generation.
 *
 * END ****************************************************************************************************************/

void BOARD_InitPPSPins(void) {
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_26_NETC_TMR_PP1,          /* GPIO_AD_26 is configured as NETC_TMR_PP1 */
      1U);
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_26_NETC_TMR_PP1,          /* GPIO_AD_26 PAD functional properties : */
      0x06U);                                  /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B2_04_NETC_TMR_PP1,       /* GPIO_SD_B2_04 is configured as NETC_TMR_PP1 */
      1U);
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_SD_B2_04_NETC_TMR_PP1,       /* GPIO_SD_B2_04 PAD functional properties : */
      0x08U);                                  /* Open Drain field: Disabled
                                                  Pull Down Pull Up Field: Pull Down
                                                  PDRV Field: high driver */
}
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: A5, peripheral: LPUART1, signal: RXD, pin_signal: GPIO_AON_09, pull_up_down_config: Pull_Down, pull_keeper_select: Keeper, open_drain: Disable, drive_strength: High,
    slew_rate: Slow}
  - {pin_num: B1, peripheral: LPUART1, signal: TXD, pin_signal: GPIO_AON_08, pull_up_down_config: Pull_Down, pull_keeper_select: Keeper, open_drain: Disable, drive_strength: High,
    slew_rate: Slow}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins, assigned for the Cortex-M33 core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc2);          /* Turn on LPCG: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AON_08_LPUART1_TX,          /* GPIO_AON_08 is configured as LPUART1_TX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AON_09_LPUART1_RX,          /* GPIO_AON_09 is configured as LPUART1_RX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AON_08_LPUART1_TX,          /* GPIO_AON_08 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Open Drain LPSR Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AON_09_LPUART1_RX,          /* GPIO_AON_09 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Open Drain LPSR Field: Disabled */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPhyAccessPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: L17, peripheral: NETC, signal: netc_emdc, pin_signal: GPIO_AD_30, pull_up_down_config: Pull_Down, open_drain: Disable}
  - {pin_num: K17, peripheral: NETC, signal: netc_emdio, pin_signal: GPIO_AD_31, pull_up_down_config: Pull_Down, open_drain: Enable}
  - {pin_num: B11, peripheral: RGPIO6, signal: 'gpio_io, 13', pin_signal: GPIO_B1_13}
  - {pin_num: M15, peripheral: RGPIO4, signal: 'gpio_io, 25', pin_signal: GPIO_AD_25}
  - {pin_num: N15, peripheral: RGPIO4, signal: 'gpio_io, 13', pin_signal: GPIO_AD_13}
  - {pin_num: L16, peripheral: RGPIO4, signal: 'gpio_io, 28', pin_signal: GPIO_AD_28}
  - {pin_num: E10, peripheral: RGPIO6, signal: 'gpio_io, 15', pin_signal: GPIO_B2_01}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPhyAccessPins, assigned for the Cortex-M33 core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPhyAccessPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */

  /* PHY4 Reset */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_13_GPIO4_IO13,           /* GPIO_AD_13 is configured as GPIO4_IO13 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  /* PHY0 Reset */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_25_GPIO4_IO25,           /* GPIO_AD_25 is configured as GPIO4_IO25 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_30_NETC_EMDC,            /* GPIO_AD_30 is configured as NETC_EMDC */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_31_NETC_EMDIO,           /* GPIO_AD_31 is configured as NETC_EMDIO */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  /* PHY1 Reset */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_13_GPIO6_IO13,           /* GPIO_B1_13 is configured as GPIO6_IO13 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  /* PHY2 Reset */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_28_GPIO4_IO28,           /* GPIO_AD_28 is configured as GPIO4_IO28 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  /* PHY3 Reset */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B2_01_GPIO6_IO15,           /* GPIO_B2_01 is configured as GPIO6_IO15 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_30_NETC_EMDC,            /* GPIO_AD_30 PAD functional properties : */
      0x06U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled
                                                 Open Drain LPSR Field: Disabled
                                                 Open Drain SNVS Field: Disabled
                                                 Force ibe off Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_31_NETC_EMDIO,           /* GPIO_AD_31 PAD functional properties : */
      0x16U);                                 /* Slew Rate Field: Fast Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Enabled
                                                 Open Drain LPSR Field: Disabled
                                                 Open Drain SNVS Field: Disabled
                                                 Force ibe off Field: Disabled */

  /* PHY1 Reset */
  /* NOTE Uncomment following lines if resistor R469 is installed */
#if 0
  IOMUXC_SetPinConfig(                       /* GPIO_B1_13 PAD functional properties : */
      IOMUXC_GPIO_B1_13_GPIO6_IO13,          /* Open Drain Field: Enabled
      0x1CU);                                    Pull Field: No Pull
                                                 PDRV Field: high driver */
#endif

  /* PHY3 Reset */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_B2_01_GPIO6_IO15,           /* GPIO_B2_01 PAD functional properties : */
      0x1CU);                                 /* Open Drain Field: Enabled
                                                 Pull Field: No Pull
                                                 PDRV Field: high driver */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSwtPort0Pins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: T7, peripheral: ETH0, signal: TX_EN, pin_signal: GPIO_EMC_B2_07}
  - {pin_num: U4, peripheral: ETH0, signal: TX_CLK, pin_signal: GPIO_EMC_B2_08, software_input_on: Enable}
  - {pin_num: T4, peripheral: ETH0, signal: 'TX_DATA, 0', pin_signal: GPIO_EMC_B2_05}
  - {pin_num: T6, peripheral: ETH0, signal: 'TX_DATA, 1', pin_signal: GPIO_EMC_B2_06}
  - {pin_num: P6, peripheral: ETH0, signal: RX_EN, pin_signal: GPIO_EMC_B2_11}
  - {pin_num: R5, peripheral: ETH0, signal: RX_ER, pin_signal: GPIO_EMC_B2_12}
  - {pin_num: U5, peripheral: ETH0, signal: 'RX_DATA, 0', pin_signal: GPIO_EMC_B2_09}
  - {pin_num: U6, peripheral: ETH0, signal: 'RX_DATA, 1', pin_signal: GPIO_EMC_B2_10}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSwtPort0Pins, assigned for the Cortex-M33 core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitSwtPort0Pins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_05_NETC_PINMUX_ETH0_TXD00,  /* GPIO_EMC_B2_05 is configured as NETC_PINMUX_ETH0_TXD00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_06_NETC_PINMUX_ETH0_TXD01,  /* GPIO_EMC_B2_06 is configured as NETC_PINMUX_ETH0_TXD01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_07_NETC_PINMUX_ETH0_TX_EN,  /* GPIO_EMC_B2_07 is configured as NETC_PINMUX_ETH0_TX_EN */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_08_NETC_PINMUX_ETH0_TX_CLK,  /* GPIO_EMC_B2_08 is configured as NETC_PINMUX_ETH0_TX_CLK */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_EMC_B2_08 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_09_NETC_PINMUX_ETH0_RXD00,  /* GPIO_EMC_B2_09 is configured as NETC_PINMUX_ETH0_RXD00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_10_NETC_PINMUX_ETH0_RXD01,  /* GPIO_EMC_B2_10 is configured as NETC_PINMUX_ETH0_RXD01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_11_NETC_PINMUX_ETH0_RX_DV,  /* GPIO_EMC_B2_11 is configured as NETC_PINMUX_ETH0_RX_DV */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_12_NETC_PINMUX_ETH0_RX_ER,  /* GPIO_EMC_B2_12 is configured as NETC_PINMUX_ETH0_RX_ER */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSwtPort1Pins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: A14, peripheral: ETH1, signal: TX_CLK, pin_signal: GPIO_B1_03}
  - {pin_num: E12, peripheral: ETH1, signal: TX_EN, pin_signal: GPIO_B1_02}
  - {pin_num: E13, peripheral: ETH1, signal: 'TX_DATA, 0', pin_signal: GPIO_B1_00}
  - {pin_num: C12, peripheral: ETH1, signal: 'TX_DATA, 1', pin_signal: GPIO_B1_01}
  - {pin_num: D13, peripheral: ETH1, signal: 'TX_DATA, 2', pin_signal: GPIO_B1_07}
  - {pin_num: B14, peripheral: ETH1, signal: 'TX_DATA, 3', pin_signal: GPIO_B1_08}
  - {pin_num: A12, peripheral: ETH1, signal: RX_CLK, pin_signal: GPIO_B1_11}
  - {pin_num: B10, peripheral: ETH1, signal: RX_EN, pin_signal: GPIO_B1_06}
  - {pin_num: B13, peripheral: ETH1, signal: 'RX_DATA, 0', pin_signal: GPIO_B1_04}
  - {pin_num: B12, peripheral: ETH1, signal: 'RX_DATA, 1', pin_signal: GPIO_B1_05}
  - {pin_num: A15, peripheral: ETH1, signal: 'RX_DATA, 2', pin_signal: GPIO_B1_09}
  - {pin_num: A13, peripheral: ETH1, signal: 'RX_DATA, 3', pin_signal: GPIO_B1_10}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSwtPort1Pins, assigned for the Cortex-M33 core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitSwtPort1Pins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_00_NETC_PINMUX_ETH1_TXD00,  /* GPIO_B1_00 is configured as NETC_PINMUX_ETH1_TXD00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_01_NETC_PINMUX_ETH1_TXD01,  /* GPIO_B1_01 is configured as NETC_PINMUX_ETH1_TXD01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_02_NETC_PINMUX_ETH1_TX_EN,  /* GPIO_B1_02 is configured as NETC_PINMUX_ETH1_TX_EN */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_03_NETC_PINMUX_ETH1_TX_CLK,  /* GPIO_B1_03 is configured as NETC_PINMUX_ETH1_TX_CLK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_04_NETC_PINMUX_ETH1_RXD00,  /* GPIO_B1_04 is configured as NETC_PINMUX_ETH1_RXD00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_05_NETC_PINMUX_ETH1_RXD01,  /* GPIO_B1_05 is configured as NETC_PINMUX_ETH1_RXD01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_06_NETC_PINMUX_ETH1_RX_DV,  /* GPIO_B1_06 is configured as NETC_PINMUX_ETH1_RX_DV */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_07_NETC_PINMUX_ETH1_TXD02,  /* GPIO_B1_07 is configured as NETC_PINMUX_ETH1_TXD02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_08_NETC_PINMUX_ETH1_TXD03,  /* GPIO_B1_08 is configured as NETC_PINMUX_ETH1_TXD03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_09_NETC_PINMUX_ETH1_RXD02,  /* GPIO_B1_09 is configured as NETC_PINMUX_ETH1_RXD02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_10_NETC_PINMUX_ETH1_RXD03,  /* GPIO_B1_10 is configured as NETC_PINMUX_ETH1_RXD03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B1_11_NETC_PINMUX_ETH1_RX_CLK,  /* GPIO_B1_11 is configured as NETC_PINMUX_ETH1_RX_CLK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSwtPort2Pins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: H1, peripheral: ETH2, signal: 'RX_DATA, 0', pin_signal: GPIO_EMC_B1_16}
  - {pin_num: E2, peripheral: ETH2, signal: 'RX_DATA, 1', pin_signal: GPIO_EMC_B1_17}
  - {pin_num: K4, peripheral: ETH2, signal: RX_CLK, pin_signal: GPIO_EMC_B1_21}
  - {pin_num: L3, peripheral: ETH2, signal: 'RX_DATA, 2', pin_signal: GPIO_EMC_B1_22}
  - {pin_num: F1, peripheral: ETH2, signal: 'RX_DATA, 3', pin_signal: GPIO_EMC_B1_23}
  - {pin_num: P2, peripheral: ETH2, signal: 'TX_DATA, 3', pin_signal: GPIO_EMC_B1_24}
  - {pin_num: N3, peripheral: ETH2, signal: 'TX_DATA, 2', pin_signal: GPIO_EMC_B1_25}
  - {pin_num: F3, peripheral: ETH2, signal: RX_EN, pin_signal: GPIO_EMC_B1_13}
  - {pin_num: N4, peripheral: ETH2, signal: 'TX_DATA, 1', pin_signal: GPIO_EMC_B1_26}
  - {pin_num: J3, peripheral: ETH2, signal: 'TX_DATA, 0', pin_signal: GPIO_EMC_B1_27}
  - {pin_num: F5, peripheral: ETH2, signal: TX_EN, pin_signal: GPIO_EMC_B1_28}
  - {pin_num: E4, peripheral: ETH2, signal: TX_CLK, pin_signal: GPIO_EMC_B1_29}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSwtPort2Pins, assigned for the Cortex-M33 core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitSwtPort2Pins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_13_NETC_PINMUX_ETH2_RX_DV,  /* GPIO_EMC_B1_13 is configured as NETC_PINMUX_ETH2_RX_DV */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_16_NETC_PINMUX_ETH2_RXD00,  /* GPIO_EMC_B1_16 is configured as NETC_PINMUX_ETH2_RXD00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_17_NETC_PINMUX_ETH2_RXD01,  /* GPIO_EMC_B1_17 is configured as NETC_PINMUX_ETH2_RXD01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_21_NETC_PINMUX_ETH2_RX_CLK,  /* GPIO_EMC_B1_21 is configured as NETC_PINMUX_ETH2_RX_CLK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_22_NETC_PINMUX_ETH2_RXD02,  /* GPIO_EMC_B1_22 is configured as NETC_PINMUX_ETH2_RXD02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_23_NETC_PINMUX_ETH2_RXD03,  /* GPIO_EMC_B1_23 is configured as NETC_PINMUX_ETH2_RXD03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_24_NETC_PINMUX_ETH2_TXD03,  /* GPIO_EMC_B1_24 is configured as NETC_PINMUX_ETH2_TXD03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_25_NETC_PINMUX_ETH2_TXD02,  /* GPIO_EMC_B1_25 is configured as NETC_PINMUX_ETH2_TXD02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_26_NETC_PINMUX_ETH2_TXD01,  /* GPIO_EMC_B1_26 is configured as NETC_PINMUX_ETH2_TXD01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_27_NETC_PINMUX_ETH2_TXD00,  /* GPIO_EMC_B1_27 is configured as NETC_PINMUX_ETH2_TXD00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_28_NETC_PINMUX_ETH2_TX_EN,  /* GPIO_EMC_B1_28 is configured as NETC_PINMUX_ETH2_TX_EN */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_29_NETC_PINMUX_ETH2_TX_CLK,  /* GPIO_EMC_B1_29 is configured as NETC_PINMUX_ETH2_TX_CLK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSwtPort3Pins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: G5, peripheral: ETH3, signal: CRS, pin_signal: GPIO_EMC_B1_14}
  - {pin_num: G2, peripheral: ETH3, signal: COL, pin_signal: GPIO_EMC_B1_15}
  - {pin_num: H3, peripheral: ETH3, signal: 'TX_DATA, 3', pin_signal: GPIO_EMC_B1_00}
  - {pin_num: H4, peripheral: ETH3, signal: 'TX_DATA, 2', pin_signal: GPIO_EMC_B1_01}
  - {pin_num: K2, peripheral: ETH3, signal: RX_CLK, pin_signal: GPIO_EMC_B1_02}
  - {pin_num: G3, peripheral: ETH3, signal: 'RX_DATA, 3', pin_signal: GPIO_EMC_B1_03}
  - {pin_num: J4, peripheral: ETH3, signal: 'RX_DATA, 2', pin_signal: GPIO_EMC_B1_04}
  - {pin_num: H6, peripheral: ETH3, signal: 'TX_DATA, 0', pin_signal: GPIO_EMC_B1_05}
  - {pin_num: K3, peripheral: ETH3, signal: 'TX_DATA, 1', pin_signal: GPIO_EMC_B1_06}
  - {pin_num: M3, peripheral: ETH3, signal: TX_EN, pin_signal: GPIO_EMC_B1_07}
  - {pin_num: H5, peripheral: ETH3, signal: TX_CLK, pin_signal: GPIO_EMC_B1_08}
  - {pin_num: E1, peripheral: ETH3, signal: 'RX_DATA, 0', pin_signal: GPIO_EMC_B1_09}
  - {pin_num: E3, peripheral: ETH3, signal: 'RX_DATA, 1', pin_signal: GPIO_EMC_B1_10}
  - {pin_num: F2, peripheral: ETH3, signal: RX_EN, pin_signal: GPIO_EMC_B1_11}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSwtPort3Pins, assigned for the Cortex-M33 core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitSwtPort3Pins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_00_NETC_PINMUX_ETH3_TXD03,  /* GPIO_EMC_B1_00 is configured as NETC_PINMUX_ETH3_TXD03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_01_NETC_PINMUX_ETH3_TXD02,  /* GPIO_EMC_B1_01 is configured as NETC_PINMUX_ETH3_TXD02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_02_NETC_PINMUX_ETH3_RX_CLK,  /* GPIO_EMC_B1_02 is configured as NETC_PINMUX_ETH3_RX_CLK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_03_NETC_PINMUX_ETH3_RXD03,  /* GPIO_EMC_B1_03 is configured as NETC_PINMUX_ETH3_RXD03 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_04_NETC_PINMUX_ETH3_RXD02,  /* GPIO_EMC_B1_04 is configured as NETC_PINMUX_ETH3_RXD02 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_05_NETC_PINMUX_ETH3_TXD00,  /* GPIO_EMC_B1_05 is configured as NETC_PINMUX_ETH3_TXD00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_06_NETC_PINMUX_ETH3_TXD01,  /* GPIO_EMC_B1_06 is configured as NETC_PINMUX_ETH3_TXD01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_07_NETC_PINMUX_ETH3_TX_EN,  /* GPIO_EMC_B1_07 is configured as NETC_PINMUX_ETH3_TX_EN */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_08_NETC_PINMUX_ETH3_TX_CLK,  /* GPIO_EMC_B1_08 is configured as NETC_PINMUX_ETH3_TX_CLK */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_09_NETC_PINMUX_ETH3_RXD00,  /* GPIO_EMC_B1_09 is configured as NETC_PINMUX_ETH3_RXD00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_10_NETC_PINMUX_ETH3_RXD01,  /* GPIO_EMC_B1_10 is configured as NETC_PINMUX_ETH3_RXD01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_11_NETC_PINMUX_ETH3_RX_DV,  /* GPIO_EMC_B1_11 is configured as NETC_PINMUX_ETH3_RX_DV */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_14_NETC_ETH3_CRS,    /* GPIO_EMC_B1_14 is configured as NETC_ETH3_CRS */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_15_NETC_ETH3_COL,    /* GPIO_EMC_B1_15 is configured as NETC_ETH3_COL */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitEpPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: R4, peripheral: ETH4, signal: TX_EN, pin_signal: GPIO_EMC_B2_15}
  - {pin_num: R7, peripheral: ETH4, signal: TX_CLK, pin_signal: GPIO_EMC_B2_16, software_input_on: Enable}
  - {pin_num: R6, peripheral: ETH4, signal: 'TX_DATA, 0', pin_signal: GPIO_EMC_B2_13}
  - {pin_num: N8, peripheral: ETH4, signal: 'TX_DATA, 1', pin_signal: GPIO_EMC_B2_14}
  - {pin_num: U8, peripheral: ETH4, signal: RX_EN, pin_signal: GPIO_EMC_B2_19}
  - {pin_num: R8, peripheral: ETH4, signal: RX_ER, pin_signal: GPIO_EMC_B2_20}
  - {pin_num: U7, peripheral: ETH4, signal: 'RX_DATA, 0', pin_signal: GPIO_EMC_B2_17}
  - {pin_num: P8, peripheral: ETH4, signal: 'RX_DATA, 1', pin_signal: GPIO_EMC_B2_18}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitEpPins, assigned for the Cortex-M33 core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitEpPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_13_NETC_PINMUX_ETH4_TXD00,  /* GPIO_EMC_B2_13 is configured as NETC_PINMUX_ETH4_TXD00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_14_NETC_PINMUX_ETH4_TXD01,  /* GPIO_EMC_B2_14 is configured as NETC_PINMUX_ETH4_TXD01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_15_NETC_PINMUX_ETH4_TX_EN,  /* GPIO_EMC_B2_15 is configured as NETC_PINMUX_ETH4_TX_EN */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_16_NETC_PINMUX_ETH4_TX_CLK,  /* GPIO_EMC_B2_16 is configured as NETC_PINMUX_ETH4_TX_CLK */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_EMC_B2_16 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_17_NETC_PINMUX_ETH4_RXD00,  /* GPIO_EMC_B2_17 is configured as NETC_PINMUX_ETH4_RXD00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_18_NETC_PINMUX_ETH4_RXD01,  /* GPIO_EMC_B2_18 is configured as NETC_PINMUX_ETH4_RXD01 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_19_NETC_PINMUX_ETH4_RX_DV,  /* GPIO_EMC_B2_19 is configured as NETC_PINMUX_ETH4_RX_DV */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_20_NETC_PINMUX_ETH4_RX_ER,  /* GPIO_EMC_B2_20 is configured as NETC_PINMUX_ETH4_RX_ER */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: A10, peripheral: FLEXSPI1, signal: FLEXSPI_A_DATA0, pin_signal: GPIO_B2_10, software_input_on: Enable}
  - {pin_num: B9, peripheral: FLEXSPI1, signal: FLEXSPI_A_DATA1, pin_signal: GPIO_B2_11, software_input_on: Enable}
  - {pin_num: A8, peripheral: FLEXSPI1, signal: FLEXSPI_A_DATA2, pin_signal: GPIO_B2_12, software_input_on: Enable}
  - {pin_num: B8, peripheral: FLEXSPI1, signal: FLEXSPI_A_DATA3, pin_signal: GPIO_B2_13, software_input_on: Enable}
  - {pin_num: A6, peripheral: FLEXSPI1, signal: FLEXSPI_A_DQS, pin_signal: GPIO_B2_07, software_input_on: Enable}
  - {pin_num: A7, peripheral: FLEXSPI1, signal: FLEXSPI_A_SCLK, pin_signal: GPIO_B2_08, software_input_on: Enable}
  - {pin_num: D10, peripheral: FLEXSPI1, signal: FLEXSPI_A_SS0_B, pin_signal: GPIO_B2_09, software_input_on: Enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitFlexSPIPins, assigned for the Cortex-M33 core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitFlexSPIPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */
  CLOCK_EnableClock(kCLOCK_Iomuxc2);          /* Turn on LPCG: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B2_07_FLEXSPI1_BUS2BIT_A_DQS,  /* GPIO_B2_07 is configured as FLEXSPI1_BUS2BIT_A_DQS */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_B2_07 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B2_08_FLEXSPI1_BUS2BIT_A_SCLK,  /* GPIO_B2_08 is configured as FLEXSPI1_BUS2BIT_A_SCLK */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_B2_08 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B2_09_FLEXSPI1_BUS2BIT_A_SS0_B,  /* GPIO_B2_09 is configured as FLEXSPI1_BUS2BIT_A_SS0_B */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_B2_09 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B2_10_FLEXSPI1_BUS2BIT_A_DATA00,  /* GPIO_B2_10 is configured as FLEXSPI1_BUS2BIT_A_DATA00 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_B2_10 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B2_11_FLEXSPI1_BUS2BIT_A_DATA01,  /* GPIO_B2_11 is configured as FLEXSPI1_BUS2BIT_A_DATA01 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_B2_11 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B2_12_FLEXSPI1_BUS2BIT_A_DATA02,  /* GPIO_B2_12 is configured as FLEXSPI1_BUS2BIT_A_DATA02 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_B2_12 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_B2_13_FLEXSPI1_BUS2BIT_A_DATA03,  /* GPIO_B2_13 is configured as FLEXSPI1_BUS2BIT_A_DATA03 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_B2_13 */
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: J1, peripheral: FLEXSPI2, signal: FLEXSPI_B_DATA1, pin_signal: GPIO_EMC_B1_32, software_input_on: Enable}
  - {pin_num: K1, peripheral: FLEXSPI2, signal: FLEXSPI_B_DATA0, pin_signal: GPIO_EMC_B1_33, software_input_on: Enable}
  - {pin_num: L1, peripheral: FLEXSPI2, signal: FLEXSPI_A_DATA0, pin_signal: GPIO_EMC_B1_35, software_input_on: Enable}
  - {pin_num: M1, peripheral: FLEXSPI2, signal: FLEXSPI_A_DATA1, pin_signal: GPIO_EMC_B1_36, software_input_on: Enable}
  - {pin_num: N1, peripheral: FLEXSPI2, signal: FLEXSPI_A_DATA2, pin_signal: GPIO_EMC_B1_37, software_input_on: Enable}
  - {pin_num: P1, peripheral: FLEXSPI2, signal: FLEXSPI_A_SS0_B, pin_signal: GPIO_EMC_B1_39, software_input_on: Enable}
  - {pin_num: H2, peripheral: FLEXSPI2, signal: FLEXSPI_B_DATA3, pin_signal: GPIO_EMC_B1_30, software_input_on: Enable}
  - {pin_num: J2, peripheral: FLEXSPI2, signal: FLEXSPI_B_DATA2, pin_signal: GPIO_EMC_B1_31, software_input_on: Enable}
  - {pin_num: N2, peripheral: FLEXSPI2, signal: FLEXSPI_A_DQS, pin_signal: GPIO_EMC_B1_40, software_input_on: Enable}
  - {pin_num: M2, peripheral: FLEXSPI2, signal: FLEXSPI_A_DATA3, pin_signal: GPIO_EMC_B1_38, software_input_on: Enable}
  - {pin_num: L2, peripheral: FLEXSPI2, signal: FLEXSPI_B_SCLK, pin_signal: GPIO_EMC_B1_34, software_input_on: Enable}
  - {pin_num: R1, peripheral: FLEXSPI2, signal: FLEXSPI_A_SCLK, pin_signal: GPIO_EMC_B1_41, software_input_on: Enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitHyperramPins, assigned for the Cortex-M33 core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/

void BOARD_InitHyperramPins(void) {

  CLOCK_EnableClock(kCLOCK_Iomuxc1);          /* Turn on LPCG: LPCG is ON. */
  CLOCK_EnableClock(kCLOCK_Iomuxc2);          /* Turn on LPCG: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_30_FLEXSPI2_BUS2BIT_B_DATA03,  /* GPIO_EMC_B1_30 is configured as FLEXSPI2_BUS2BIT_B_DATA03 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_EMC_B1_30 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_31_FLEXSPI2_BUS2BIT_B_DATA02,  /* GPIO_EMC_B1_31 is configured as FLEXSPI2_BUS2BIT_B_DATA02 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_EMC_B1_31 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_32_FLEXSPI2_BUS2BIT_B_DATA01,  /* GPIO_EMC_B1_32 is configured as FLEXSPI2_BUS2BIT_B_DATA01 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_EMC_B1_32 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_33_FLEXSPI2_BUS2BIT_B_DATA00,  /* GPIO_EMC_B1_33 is configured as FLEXSPI2_BUS2BIT_B_DATA00 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_EMC_B1_33 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_34_FLEXSPI2_BUS2BIT_B_SCLK,  /* GPIO_EMC_B1_34 is configured as FLEXSPI2_BUS2BIT_B_SCLK */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_EMC_B1_34 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_35_FLEXSPI2_BUS2BIT_A_DATA00,  /* GPIO_EMC_B1_35 is configured as FLEXSPI2_BUS2BIT_A_DATA00 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_EMC_B1_35 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_36_FLEXSPI2_BUS2BIT_A_DATA01,  /* GPIO_EMC_B1_36 is configured as FLEXSPI2_BUS2BIT_A_DATA01 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_EMC_B1_36 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_37_FLEXSPI2_BUS2BIT_A_DATA02,  /* GPIO_EMC_B1_37 is configured as FLEXSPI2_BUS2BIT_A_DATA02 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_EMC_B1_37 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_38_FLEXSPI2_BUS2BIT_A_DATA03,  /* GPIO_EMC_B1_38 is configured as FLEXSPI2_BUS2BIT_A_DATA03 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_EMC_B1_38 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_39_FLEXSPI2_BUS2BIT_A_SS0_B,  /* GPIO_EMC_B1_39 is configured as FLEXSPI2_BUS2BIT_A_SS0_B */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_EMC_B1_39 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_40_FLEXSPI2_BUS2BIT_A_DQS,  /* GPIO_EMC_B1_40 is configured as FLEXSPI2_BUS2BIT_A_DQS */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_EMC_B1_40 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B1_41_FLEXSPI2_BUS2BIT_A_SCLK,  /* GPIO_EMC_B1_41 is configured as FLEXSPI2_BUS2BIT_A_SCLK */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_EMC_B1_41 */
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
