/*
 * Copyright 2023-2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);
 
/* GPIO_AON_19 (coord D5), LPUART12_TXD/DC_RESET/ENET2_INT_B/U61[6]/J47[7]/U29[31]/U73[5] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART12_TXD_PERIPHERAL                          LPUART12   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART12_TXD_SIGNAL                                   TXD   /*!< Signal name */

/* GPIO_AON_20 (coord E5), LPUART12_RXD/BT_DEV_WAKE/DC_GPIO1/U61[5]/J47[21]/U43[9] */
/* Routed pin properties */
#define BOARD_INITPINS_LPUART12_RXD_PERIPHERAL                          LPUART12   /*!< Peripheral name */
#define BOARD_INITPINS_LPUART12_RXD_SIGNAL                                   RXD   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

#ifdef CONFIG_APP_MOTOR_IO_DEVICE
/* GPIO_AD_06 (coord N13), CUR_A */
/* Routed pin properties */
#define BOARD_INITADC_CUR_A1_PERIPHERAL                                     ADC1   /*!< Peripheral name */
#define BOARD_INITADC_CUR_A1_SIGNAL                                            A   /*!< Signal name */
#define BOARD_INITADC_CUR_A1_CHANNEL                                          1U   /*!< Signal channel */

/* GPIO_AD_21 (coord K15), CUR_A */
/* Routed pin properties */
#define BOARD_INITADC_CUR_A2_PERIPHERAL                                     ADC2   /*!< Peripheral name */
#define BOARD_INITADC_CUR_A2_SIGNAL                                            B   /*!< Signal name */
#define BOARD_INITADC_CUR_A2_CHANNEL                                          2U   /*!< Signal channel */

/* GPIO_AD_07 (coord T17), CUR_B */
/* Routed pin properties */
#define BOARD_INITADC_CUR_B_PERIPHERAL                                      ADC1   /*!< Peripheral name */
#define BOARD_INITADC_CUR_B_SIGNAL                                             B   /*!< Signal name */
#define BOARD_INITADC_CUR_B_CHANNEL                                           1U   /*!< Signal channel */

/* GPIO_AD_22 (coord K12), CUR_C */
/* Routed pin properties */
#define BOARD_INITADC_CUR_C_PERIPHERAL                                      ADC2   /*!< Peripheral name */
#define BOARD_INITADC_CUR_C_SIGNAL                                             A   /*!< Signal name */
#define BOARD_INITADC_CUR_C_CHANNEL                                           2U   /*!< Signal channel */

/* GPIO_AD_09 (coord R16), VOLT_DCB */
/* Routed pin properties */
#define BOARD_INITADC_VOLT_DCB_PERIPHERAL                                   ADC1   /*!< Peripheral name */
#define BOARD_INITADC_VOLT_DCB_SIGNAL                                          B   /*!< Signal name */
#define BOARD_INITADC_VOLT_DCB_CHANNEL                                        1U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitADC(void);                     /* Function assigned for the Cortex-M7F */

/* GPIO_AD_00 (coord N12), PWM_AT */
/* Routed pin properties */
#define BOARD_INITPWM_PWM_AT_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPWM_PWM_AT_SIGNAL                                            A   /*!< Signal name */
#define BOARD_INITPWM_PWM_AT_CHANNEL                                          0U   /*!< Signal channel */

/* GPIO_AD_01 (coord R14), PWM_AB */
/* Routed pin properties */
#define BOARD_INITPWM_PWM_AB_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPWM_PWM_AB_SIGNAL                                            B   /*!< Signal name */
#define BOARD_INITPWM_PWM_AB_CHANNEL                                          0U   /*!< Signal channel */

/* GPIO_AD_02 (coord R13), PWM_BT */
/* Routed pin properties */
#define BOARD_INITPWM_PWM_BT_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPWM_PWM_BT_SIGNAL                                            A   /*!< Signal name */
#define BOARD_INITPWM_PWM_BT_CHANNEL                                          1U   /*!< Signal channel */

/* GPIO_AD_03 (coord R15), PWM_BB */
/* Routed pin properties */
#define BOARD_INITPWM_PWM_BB_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPWM_PWM_BB_SIGNAL                                            B   /*!< Signal name */
#define BOARD_INITPWM_PWM_BB_CHANNEL                                          1U   /*!< Signal channel */

/* GPIO_AD_05 (coord P13), PWM_CT */
/* Routed pin properties */
#define BOARD_INITPWM_PWM_CT_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPWM_PWM_CT_SIGNAL                                            A   /*!< Signal name */
#define BOARD_INITPWM_PWM_CT_CHANNEL                                          2U   /*!< Signal channel */

/* GPIO_AD_04 (coord P15), PWM_CB */
/* Routed pin properties */
#define BOARD_INITPWM_PWM_CB_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPWM_PWM_CB_SIGNAL                                            B   /*!< Signal name */
#define BOARD_INITPWM_PWM_CB_CHANNEL                                          2U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPWM(void);                     /* Function assigned for the Cortex-M7F */


#define XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_17_IOMUX 0x00U /*!< IOMUXC XBAR_INOUT17 function direction select: XBAR_INOUT as input */
#define XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_18_IOMUX 0x00U /*!< IOMUXC XBAR_INOUT18 function direction select: XBAR_INOUT as input */
#define XBAR_DIR_CTRL1_IOMUXC_XBAR_DIR_SEL_19_IOMUX 0x00U /*!< IOMUXC XBAR_INOUT19 function direction select: XBAR_INOUT as input */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitENC(void);                     /* Function assigned for the Cortex-M7F */

#endif /* CONFIG_APP_MOTOR_IO_DEVICE*/

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
