CONFIG_MCUX_COMPONENT_component.ele_crypto=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.ele_s4xx_rng=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.osal=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.osal.frtos=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.x509=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.crypto=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.ssl.no_psa=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.crypto.no_psa=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.port.config=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.port.psa_crypto_config=n
