/*
 * Copyright 2019-2020 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _MEDIA_STACK_CONFIG_
#define _MEDIA_STACK_CONFIG_

#include "fsl_common.h"

#define SAI_MAX_INSTANCES FSL_FEATURE_SOC_I2S_COUNT
#define I2C_MAX_INSTANCES FSL_FEATURE_SOC_LPI2C_COUNT
#define DMA_MAX_INSTANCES FSL_FEATURE_SOC_EDMA_COUNT
#define DMA_MAX_CHANNELS FSL_FEATURE_EDMA_MODULE_CHANNEL
#define CODEC_MAX_INSTANCES 2

#define AUDIO_DEVICE_MAX_PLAYBACK_INSTANCES 4
#define AUDIO_DEVICE_MAX_CAPTURE_INSTANCES 4

#define CODEC_NO_DEV_INSTANCE (CODEC_MAX_INSTANCES - 1)

#endif /* _MEDIA_STACK_CONFIG_ */
