if (CONFIG_MCUX_PRJSEG_config.board.avb_audio_app)
    mcux_add_include(
        INCLUDES
        .
    )

    mcux_add_source(
        SOURCES
        audio.c
        audio.h
        audio_config.c
        audio_config.h
        audio_stream.c
        audio_stream.h
        avb_audio_app.c
        avb_audio_app.h
        avb_stream.c
        avb_stream.h
        avb_stream_config.c
        avb_stream_config.h
        clock_domain.c
        clock_domain.h
        configs.c
        crf_stream.c
        crf_stream.h
        msrp.c
        msrp.h
        shell.c
        task_config.c
        task_config.h
        task_management.c
        task_management.h
        media_stack/audio_device.c
        media_stack/audio_device.h
        media_stack/codec.c
        media_stack/codec.h
        media_stack/common.h
        media_stack/dma.c
        media_stack/dma.h
        media_stack/fsl_wm8960.c
        media_stack/fsl_wm8960.h
        media_stack/fsl_wm8962.c
        media_stack/fsl_wm8962.h
        media_stack/i2c.c
        media_stack/i2c.h
        media_stack/sai.c
        media_stack/sai.h
    )
endif()

include(${app_board_prj_path}/mcux_lib_variable.cmake OPTIONAL)
