mcux_add_source(
    SOURCES
    main.c
)

mcux_add_macro(
    CC "__STARTUP_INITIALIZE_NONCACHEDATA\
        __STARTUP_INITIALIZE_QADATA\
        __STARTUP_INITIALIZE_RAMFUNCTION\
        DEBUG_CONSOLE_TRANSMIT_BUFFER_LEN=16384\
        __STARTUP_CLEAR_BSS\
        FSL_ETH_ENABLE_CACHE_CONTROL"
)
